name: Compila e Pubblica su GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Imposta Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login a GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Aggiorna il file deployment.yaml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          python3 -c '
          import re
          long_sha = ${{github.sha}}
          sha = long_sha[0,4]
          with open("nginx-log-creator/deployment.yaml", "r") as f:
              content = f.read()
          # Sostituisce la riga dell immagine con il nuovo SHA
          new_content = re.sub(r"image: ghcr\.io/.*?/.*", "image: ghcr.io/zcchnt/fleet-edge-apps:"+sha, content)
          with open("nginx-log-creator/deployment.yaml", "w") as f:
              f.write(new_content)
          '
          
          git commit -am "Aggiorna immagine a "+ sha
          git push


      - name: Build e Push dell'immagine
        uses: docker/build-push-action@v5
        with:
          context: ./automatic-log       
          file: ./automatic-log/Dockerfile 
          push: true
          tags: ghcr.io/zcchnt/fleet-edge-apps:${{ github.sha }}