name: Compila e Pubblica su GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Imposta Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login a GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Estrai i primi 7 caratteri dello SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Aggiorna il file deployment.yaml
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        python3 -c '
        import re, os
        sha = os.environ["SHORT_SHA"]
        with open("nginx-log-creator/deployment.yaml", "r") as f:
            content = f.read()
        new_content = re.sub(r"image: ghcr\.io/.*?/.*", f"image: ghcr.io/zcchnt/fleet-edge-apps:{sha}", content)
        with open("nginx-log-creator/deployment.yaml", "w") as f:
            f.write(new_content)
        '
        
        git commit -am "Aggiorna immagine a $SHORT_SHA"
        git push
      env:
        SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}


      - name: Build e Push dell'immagine
        uses: docker/build-push-action@v5
        with:
          context: ./automatic-log       
          file: ./automatic-log/Dockerfile 
          push: true
          tags: |
            ghcr.io/zcchnt/fleet-edge-apps:${{ steps.vars.outputs.SHORT_SHA }}
            ghcr.io/zcchnt/fleet-edge-apps:latest